[package]
name = "ez-redirects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

regex = "1.4"
walkdir = "2.3"
chrono = "0.4.19"
algoliasearch = "0.8.0"